### ISSUE TITLE
Sie und Du

### ISSUE THREAD

**Issue by lschiesser** [lschiesser/pragmatics_rep#3]
Realisieren wir eigentlich das "Sie" und "Du" in dem Experiment, weil Caro hat ja bis jetzt alles mit du/dein übersetzt (was ja auch nicht falsch war). Aber realisieren wir müssen ja auch die Höflichkeitsform realisieren, nicht nur die Direktform.
Fragen:

1.  Soll die Höflichkeitsform überhaupt überprüft werden?
2.  Wenn ja sollen die voneinander getrennt geprüft werden oder sollen die am besten gemischt werden?

**Comment by ma-zeller** [comment]
Hi! habs zu spät gesehen

**Comment by ma-zeller** [comment]
Also in dem hauptding steht schon sie

**Comment by lschiesser** [comment]
Also es geht vor allem um die Stelle:

> [name2] möchte [goal] sein und antwortet: „Deine Präsentation war [utterance].“ 

Und da vor allem um "Deine ...", weil das ist ja nur die Direktform, aber, so wie ich das verstanden habe, will Polina ja auch die Höflichkeitsform (also "Ihre ...") abprüfen..
Da müsste man wirklich nicht mehr viel ändern, also nur jeweils "Deine" durch "Ihre" ersetzen.

**Comment by polina-tsvilodub** [comment]
Sorry, dass ich so lange zum Antworten brauchte :D Ich habe das jetzt noch gar nicht machen wollen, weil man ja zuerst eine Baseline Studie braucht. Ich glaube, es wäre am besten, einfach "**Die** Präsentation" zu schreiben. Tut mir leid, dass das  jetzt nochmal  geändert werden muss ://

**Comment by lschiesser** [comment]
Ok 👍 
Dann muss das nur noch abgeändert werden.

**Comment by lschiesser** [comment]
Ok 👍 
@ma-zeller das müsstest du dann nur noch in deinem Programm abändern

**Comment by ma-zeller** [comment]
alles gut wird gemacht

**Comment by ma-zeller** [comment]
uhh das wird bisschen eklig wegen der die und das, die hatten das problem nicht da es jeweils nur "your" war

**Comment by ma-zeller** [comment]
ist auch jetzt schon problematisch wegen dein und deine

**Comment by ma-zeller** [comment]
nvm hab eine extra grammar rule für die pronomen gemacht

**Comment by ma-zeller** [comment]
klappt alles

**Comment by ma-zeller** [comment]
wär cool wenn jemand rausfindet wie man äöü etc zum laufen bekommt

**Comment by ma-zeller** [comment]
Aaaalso, hab eine extra grammar rule für die pronomen gemacht und utf8 eingebunden damit die umlaute richtig angezeigt werden!
