### ISSUE TITLE
Trial data Erfassung

### ISSUE THREAD

**Issue by lschiesser** [lschiesser/pragmatics_rep#5]
Hey,
ich hab ja wie gesagt mir schon ein bisschen was wegen der Custom View Programmierung angeschaut. Natürlich muss man instanzieren welche Daten gesammelt werden sollen während der Durchführung des Experiments.
Ich hab ein Markdown file mit mehr Informationen dafür erstellt.
[trial_coding_specs.md](https://github.com/lschiesser/pragmatics_rep/blob/master/trial_coding_specs.md)
Sind die Daten, die ich bis jetzt vorgeschlagen habe, genug oder brauchen wir noch welche, damit die Analyse durchgeführt werden kann?

**Comment by polina-tsvilodub** [comment]
Das sieht schonmal sehr gut aus, ich brauche nur noch die Reaktionszeit, Muttersprache, Szenario und submission ID. Dabei denke ich, dass die Basisinfos wie ID, Muttersprache etc sowieso von babe ausgespuckt werden.

**Comment by lschiesser** [comment]
👍 
Ja genau
Muttersprache und ID werden von babe am Ende abgefragt bzw. erstellt
Dann muss nur die RT Zeit dazugefügt werden

**Comment by lschiesser** [comment]
@polina-tsvilodub Was meinst du mit Szenario?
